/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookDto
 */
export interface BookDto {
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    genre?: BookDtoGenreEnum;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    coverURL?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    description?: string;
}


/**
 * @export
 */
export const BookDtoGenreEnum = {
    Adventure: 'ADVENTURE',
    Action: 'ACTION',
    Fantasy: 'FANTASY',
    Fiction: 'FICTION',
    History: 'HISTORY',
    Horror: 'HORROR',
    Mystery: 'MYSTERY',
    Romance: 'ROMANCE',
    Science: 'SCIENCE',
    Sf: 'SF',
    Thriller: 'THRILLER',
    Other: 'OTHER'
} as const;
export type BookDtoGenreEnum = typeof BookDtoGenreEnum[keyof typeof BookDtoGenreEnum];


/**
 * Check if a given object implements the BookDto interface.
 */
export function instanceOfBookDto(value: object): value is BookDto {
    return true;
}

export function BookDtoFromJSON(json: any): BookDto {
    return BookDtoFromJSONTyped(json, false);
}

export function BookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'author': json['author'] == null ? undefined : json['author'],
        'genre': json['genre'] == null ? undefined : json['genre'],
        'coverURL': json['coverURL'] == null ? undefined : json['coverURL'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function BookDtoToJSON(json: any): BookDto {
    return BookDtoToJSONTyped(json, false);
}

export function BookDtoToJSONTyped(value?: BookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
        'genre': value['genre'],
        'coverURL': value['coverURL'],
        'description': value['description'],
    };
}

