/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRecord
 */
export interface LoginRecord {
    /**
     * 
     * @type {string}
     * @memberof LoginRecord
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRecord
     */
    password: string;
}

/**
 * Check if a given object implements the LoginRecord interface.
 */
export function instanceOfLoginRecord(value: object): value is LoginRecord {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginRecordFromJSON(json: any): LoginRecord {
    return LoginRecordFromJSONTyped(json, false);
}

export function LoginRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginRecordToJSON(json: any): LoginRecord {
    return LoginRecordToJSONTyped(json, false);
}

export function LoginRecordToJSONTyped(value?: LoginRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

