/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponseRecord } from './LoginResponseRecord';
import {
    LoginResponseRecordFromJSON,
    LoginResponseRecordFromJSONTyped,
    LoginResponseRecordToJSON,
    LoginResponseRecordToJSONTyped,
} from './LoginResponseRecord';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface LoginResponseRecordRequestResponse
 */
export interface LoginResponseRecordRequestResponse {
    /**
     * 
     * @type {LoginResponseRecord}
     * @memberof LoginResponseRecordRequestResponse
     */
    readonly response?: LoginResponseRecord | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof LoginResponseRecordRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the LoginResponseRecordRequestResponse interface.
 */
export function instanceOfLoginResponseRecordRequestResponse(value: object): value is LoginResponseRecordRequestResponse {
    return true;
}

export function LoginResponseRecordRequestResponseFromJSON(json: any): LoginResponseRecordRequestResponse {
    return LoginResponseRecordRequestResponseFromJSONTyped(json, false);
}

export function LoginResponseRecordRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseRecordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : LoginResponseRecordFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function LoginResponseRecordRequestResponseToJSON(json: any): LoginResponseRecordRequestResponse {
    return LoginResponseRecordRequestResponseToJSONTyped(json, false);
}

export function LoginResponseRecordRequestResponseToJSONTyped(value?: Omit<LoginResponseRecordRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

