/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecord } from './UserRecord';
import {
    UserRecordFromJSON,
    UserRecordFromJSONTyped,
    UserRecordToJSON,
    UserRecordToJSONTyped,
} from './UserRecord';

/**
 * 
 * @export
 * @interface UserFileRecord
 */
export interface UserFileRecord {
    /**
     * 
     * @type {string}
     * @memberof UserFileRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserFileRecord
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserFileRecord
     */
    description?: string | null;
    /**
     * 
     * @type {UserRecord}
     * @memberof UserFileRecord
     */
    user: UserRecord;
    /**
     * 
     * @type {Date}
     * @memberof UserFileRecord
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserFileRecord
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UserFileRecord interface.
 */
export function instanceOfUserFileRecord(value: object): value is UserFileRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserFileRecordFromJSON(json: any): UserFileRecord {
    return UserFileRecordFromJSONTyped(json, false);
}

export function UserFileRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFileRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'user': UserRecordFromJSON(json['user']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UserFileRecordToJSON(json: any): UserFileRecord {
    return UserFileRecordToJSONTyped(json, false);
}

export function UserFileRecordToJSONTyped(value?: UserFileRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'user': UserRecordToJSON(value['user']),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

