/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRecordPagedResponse } from './UserRecordPagedResponse';
import {
    UserRecordPagedResponseFromJSON,
    UserRecordPagedResponseFromJSONTyped,
    UserRecordPagedResponseToJSON,
    UserRecordPagedResponseToJSONTyped,
} from './UserRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserRecordPagedResponseRequestResponse
 */
export interface UserRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {UserRecordPagedResponse}
     * @memberof UserRecordPagedResponseRequestResponse
     */
    readonly response?: UserRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserRecordPagedResponseRequestResponse interface.
 */
export function instanceOfUserRecordPagedResponseRequestResponse(value: object): value is UserRecordPagedResponseRequestResponse {
    return true;
}

export function UserRecordPagedResponseRequestResponseFromJSON(json: any): UserRecordPagedResponseRequestResponse {
    return UserRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function UserRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserRecordPagedResponseRequestResponseToJSON(json: any): UserRecordPagedResponseRequestResponse {
    return UserRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function UserRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<UserRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

