/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateRecord
 */
export interface UserUpdateRecord {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRecord
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateRecord
     */
    password?: string | null;
}

/**
 * Check if a given object implements the UserUpdateRecord interface.
 */
export function instanceOfUserUpdateRecord(value: object): value is UserUpdateRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserUpdateRecordFromJSON(json: any): UserUpdateRecord {
    return UserUpdateRecordFromJSONTyped(json, false);
}

export function UserUpdateRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserUpdateRecordToJSON(json: any): UserUpdateRecord {
    return UserUpdateRecordToJSONTyped(json, false);
}

export function UserUpdateRecordToJSONTyped(value?: UserUpdateRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'password': value['password'],
    };
}

