/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFileRecordPagedResponse } from './UserFileRecordPagedResponse';
import {
    UserFileRecordPagedResponseFromJSON,
    UserFileRecordPagedResponseFromJSONTyped,
    UserFileRecordPagedResponseToJSON,
    UserFileRecordPagedResponseToJSONTyped,
} from './UserFileRecordPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
    ErrorMessageToJSONTyped,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface UserFileRecordPagedResponseRequestResponse
 */
export interface UserFileRecordPagedResponseRequestResponse {
    /**
     * 
     * @type {UserFileRecordPagedResponse}
     * @memberof UserFileRecordPagedResponseRequestResponse
     */
    readonly response?: UserFileRecordPagedResponse | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof UserFileRecordPagedResponseRequestResponse
     */
    readonly errorMessage?: ErrorMessage | null;
}

/**
 * Check if a given object implements the UserFileRecordPagedResponseRequestResponse interface.
 */
export function instanceOfUserFileRecordPagedResponseRequestResponse(value: object): value is UserFileRecordPagedResponseRequestResponse {
    return true;
}

export function UserFileRecordPagedResponseRequestResponseFromJSON(json: any): UserFileRecordPagedResponseRequestResponse {
    return UserFileRecordPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function UserFileRecordPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFileRecordPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : UserFileRecordPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function UserFileRecordPagedResponseRequestResponseToJSON(json: any): UserFileRecordPagedResponseRequestResponse {
    return UserFileRecordPagedResponseRequestResponseToJSONTyped(json, false);
}

export function UserFileRecordPagedResponseRequestResponseToJSONTyped(value?: Omit<UserFileRecordPagedResponseRequestResponse, 'response'|'errorMessage'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

