/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Book,
  BookDto,
} from '../models/index';
import {
    BookFromJSON,
    BookToJSON,
    BookDtoFromJSON,
    BookDtoToJSON,
} from '../models/index';

export interface AddBookRequest {
    bookDto: BookDto;
}

export interface GetBooksByAuthorRequest {
    author: string;
}

/**
 * 
 */
export class BookControllerApi extends runtime.BaseAPI {

    /**
     */
    async addBookRaw(requestParameters: AddBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        if (requestParameters['bookDto'] == null) {
            throw new runtime.RequiredError(
                'bookDto',
                'Required parameter "bookDto" was null or undefined when calling addBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/addBook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookDtoToJSON(requestParameters['bookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     */
    async addBook(requestParameters: AddBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.addBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBooksByAuthorRaw(requestParameters: GetBooksByAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookDto>>> {
        if (requestParameters['author'] == null) {
            throw new runtime.RequiredError(
                'author',
                'Required parameter "author" was null or undefined when calling getBooksByAuthor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/book/getByAuthor`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookDtoFromJSON));
    }

    /**
     */
    async getBooksByAuthor(requestParameters: GetBooksByAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookDto>> {
        const response = await this.getBooksByAuthorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
